// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using project3data.Data;
using System;

namespace project3data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180327173708_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("project3data.Models.BicycleCrime", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("caseNumber");

                    b.Property<TimeSpan>("crimeTime");

                    b.Property<int?>("districtid");

                    b.Property<DateTime>("registerDate");

                    b.HasKey("id");

                    b.HasIndex("districtid");

                    b.ToTable("BicycleCrimes");
                });

            modelBuilder.Entity("project3data.Models.District", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("areas");

                    b.Property<decimal?>("latitude");

                    b.Property<decimal?>("longitude");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("project3data.Models.StreetCrime", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("caseNumber");

                    b.Property<TimeSpan>("crimeTime");

                    b.Property<int?>("districtid");

                    b.Property<DateTime>("registerDate");

                    b.HasKey("id");

                    b.HasIndex("districtid");

                    b.ToTable("StreetCrimes");
                });

            modelBuilder.Entity("project3data.Models.BicycleCrime", b =>
                {
                    b.HasOne("project3data.Models.District", "district")
                        .WithMany()
                        .HasForeignKey("districtid");
                });

            modelBuilder.Entity("project3data.Models.StreetCrime", b =>
                {
                    b.HasOne("project3data.Models.District", "district")
                        .WithMany()
                        .HasForeignKey("districtid");
                });
#pragma warning restore 612, 618
        }
    }
}
